# Generated by Django 4.1.2 on 2022-11-13 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Escuela', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notas',
            old_name='apellido',
            new_name='materia',
        ),
    ]
